---
title: "Biorplot Documentation"
author: "Zheng Hu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
description: |
  This is a minimal example of using the bookdown package to write a book.
  set in the _output.yml file.
  The HTML output format for this example is bookdown::gitbook,
link-citations: yes
github-repo: rstudio/bookdown-demo
---


# Installation & Usage

You can download the package from [Biorplot GitHub Page](https://github.com/zhenghu159/Biorplot):\
```{r,eval = FALSE}
git clone https://github.com/zhenghu159/Biorplot.git
```
Then load the package by:\
```{r,eval = FALSE}
source('Biorplot.R')
```

## Dependence

You should install these dependence:\
[scales](https://github.com/r-lib/scales), [ggsci](https://github.com/nanxstats/ggsci), 
[ggthemes](https://github.com/jrnold/ggthemes), [ggplot2](https://github.com/tidyverse/ggplot2), 
[cowplot](https://github.com/wilkelab/cowplot), [ggrepel](https://github.com/slowkow/ggrepel)
```{r,eval = FALSE}
install.packages(c("scales","ggsci","ggthemes","ggplot2","cowplot","ggrepel"))
```

## example



